version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # expose local port
    volumes:
      - .:/usr/src/app # mount local working directory for live reload
      - /usr/src/app/node_modules # mount node_modules for caching
    depends_on:
      - mongo # wait for mongo service container
    environment:
      - MONGODB_URI=mongodb://mongo:27017/order-tracker # mongo container address

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server: # Define your new service here
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/usr/server # Mount local working directory for live reload
    depends_on:
      - mongo # Wait for mongo service container
    environment:
      - MONGODB_URI=mongodb://mongo:27017/order-tracker # mongo container address

volumes:
  mongo-data:
